export enum WorkOrderStatusEnum {
  RECEIVED = 'RECEIVED',
  DIAGNOSING = 'DIAGNOSING',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  IN_PROGRESS = 'IN_PROGRESS',
  FINISHED = 'FINISHED',
  DELIVERED = 'DELIVERED',
  REJECTED = 'REJECTED',
}
